sudo: required
dist: trusty
language: php

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  # Build the code base.
  - composer install --no-interaction --no-progress --no-suggest
  # Add Composer's local bin directory to the PATH.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
  # Register the Drupal and DrupalPractice Standard with PHPCS.
  - phpcs --config-set installed_paths $TRAVIS_BUILD_DIR/vendor/drupal/coder/coder_sniffer
script:
  - composer validate --no-check-all --ansi
  # Check Drupal coding standards.
  - phpcs --standard=Drupal --colors --ignore=*/css/*,*/vendor/* .
  # Check Drupal best practices.
  - phpcs --standard=DrupalPractice --colors --ignore=*/css/*,*/vendor/* .

matrix:
  fast_finish: true